### ISSUE TITLE
Unable to decode storage system.account [Error]

### ISSUE THREAD

**Issue by JosephKnecht-lab** [paritytech/canvas-node#50] opened 2021-06-02 08:15 UTC
I have the following error when deploying the Flipper contract on a local substrate node. Does anyone what is the cause and how to solve this issue? 

`
Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (76 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
`

**Comment by rise0chen** [comment] 2021-06-18 07:07
I have the same question.

**Comment by ascjones** [comment] 2021-06-18 08:18
Possibly a mismatch between the UI and the version of substrate your `canvas-node` is using. Can you detail which version of `canvas-node` you are using?

**Comment by JosephKnecht-lab** [comment] 2021-06-18 09:20
`2021-06-18 11:14:27 Running in --dev mode, RPC CORS has been disabled.    
2021-06-18 11:14:27 Canvas Node    
2021-06-18 11:14:27 ✌️  version 0.1.0-543a909-aarch64-macos    
2021-06-18 11:14:27 ❤️  by Canvas, 2020-2021    
2021-06-18 11:14:27 📋 Chain specification: Development    
2021-06-18 11:14:27 🏷 Node name: delightful-government-2483 `

Probably there was a mismatch in the versions. I tried to deploy the contract again, and now it is working.

**Comment by garrettmaring** [comment] 2021-06-19 04:19
I am getting this error when rynning node version `version 3.0.0-0f36d98-x86_64-macos`

**Comment by cmichi** [comment] 2021-07-14 11:48
Could you please retry with the latest `canvas-node` release?
```
cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.9 --force --locked
```

Also: Can you reproduce this when you connect [the published `canvas-ui`](https://paritytech.github.io/canvas-ui/#/) to your local node?

**Comment by garrettmaring** [comment] 2021-07-15 22:44
Will try this later and update! I've been working around it for a bit by using https://polkadot.js.org/apps/ which shows the errors during the contract uploads but still allows uploading (and interactions still work). Will be great to get canvas working again locally

**Comment by cmichi** [comment] 2021-07-20 16:16
I'm closing the issue, since I think it should be resolved with the latest release. Feel free to reopen otherwise!

**Closed by cmichi** 2021-07-20 16:16 UTC
